### ISSUE TITLE
Cannot create a new connection using `Connection Wizard`

### ISSUE THREAD

**Issue by BetimBeja** [MscrmTools/MscrmTools.Xrm.Connection#130]
It throws an error after I specify the organization url.
```
System.Exception: Unable to read user password
at McTools.Xrm.Connection.ConnectionDetail.ConnectOnline()
at McTools.Xrm.Connection.ConnectionDetail.GetCrmServiceClient(Boolean forceNewService)
at McTools.Xrm.Connection.WinForms.ConnectionWizard2.<>c.<Connect>b__18_0(Object bwSender, DoWorkEventArgs evt)
at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs evt)
at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
I am attaching a video capture of the steps to reproduce

https://user-images.githubusercontent.com/11160171/104822500-39296780-5843-11eb-8692-ccccd6d0a446.mp4

Also, XrmToolBox version is 1.2021.1.44 and the connection controls version is 1.2021.1.39

**Comment by BetimBeja** [comment]
After some more debugging I noticed that the `Use your current credentials` is checked by default, but the `Organization Url` is an online instance.
I believe that in this case you should consider the `Organization Url` as an on-premise instance or you should ignore the `Use your current credentials` flag when the url is online.

**Comment by MscrmTools** [comment]
Yes, it seems something went wrong with this checkbox. Will look at it

Thanks

**Comment by BetimBeja** [comment]
Closing this as it is fixed in the latest release
