### ISSUE TITLE
Update connection fails

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.Xrm.Connection#157]
Try a few times, can't do it...
See: https://www.screencast.com/t/beBQnsQJ

Stack:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at McTools.Xrm.Connection.ConnectionDetail.IsConnectionBrokenWithUpdatedData(ConnectionDetail originalDetail)
   at McTools.Xrm.Connection.WinForms.ConnectionWizard2.btnNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by MscrmTools** [comment]
crap! I reproduced. I will fix it right now

**Comment by rappen** [comment]
That happens....

🤞🤞

**Comment by MscrmTools** [comment]
The strange part is this portion of code that fails has not been updated since months...
I just don't get it how it fails now... it's because Certificate property is null. Well, it has always been like this for connection without certificate...
Anyway, I released a new version of connection controls

**Comment by rappen** [comment]
Sometimes it's just magic...
