### ISSUE TITLE
Beta 1.2024.2.57 can't connect to anything

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.Xrm.Connection#162]
Just updated connections to 1.2024.2.57-beta and I can't connect to anyone.
Tested:
* email/pwd
![image](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/assets/2572253/d8030ccb-012b-4fd0-af48-21dfabfd3e12)

* Client Id/Secret
* AOuth
![image](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/assets/2572253/da7948b1-ead9-4189-968b-a34311da473d)

Tried to create a new connection, same issues.

Log:
```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	2024-02-13 09:01:56  Initialize CRM connection Started - AuthType: OAuth
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	2024-02-13 09:01:56  Direct Login Process Started
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	2024-02-13 09:01:56  Attempting to Connect to Uri https://xxxx.crm4.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	2024-02-13 09:01:56  DiscoveryServer indicated organization service location = https://xxxx.crm4.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	2024-02-13 09:01:56  Organization Service URI is = https://xxxx.crm4.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	2024-02-13 09:01:56  ConnectAndInitCrmOrgService - Initializing Organization Service Object
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	2024-02-13 09:01:56  ConnectAndInitCrmOrgService - Requesting connection to Organization with CRM Version: No organization data available
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Warning	4	2024-02-13 09:01:56  AuthenticateService - Resource URI is null
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	2024-02-13 09:01:56  AuthenticateService - found authority with name https://login.microsoftonline.com/41008518-7d60-488e-8b69-c3bdd728a63c/
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	2024-02-13 09:01:56  AuthenticateService - found resource with name https://xxxx.crm4.dynamics.com/
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	2024-02-13 09:01:56  ObtainAccessToken - PROMPT - Behavior: Auto
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	2024-02-13 09:01:56  Added WebClient Header Hooks to the Request object.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	2024-02-13 09:01:56  ConnectAndInitCrmOrgService - Proxy created, total elapsed time: 00:00:00.1855204
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2024-02-13 09:01:56  Unable to connect to CRM: Method not found: 'System.String Microsoft.Xrm.Sdk.Organization.OrganizationDetail.get_SchemaType()'.
Source	: Microsoft.Xrm.Tooling.Connector
Method	: RefreshInstanceDetails
Date	: 2024-02-13
Time	: 09:01:56
Error	: Method not found: 'System.String Microsoft.Xrm.Sdk.Organization.OrganizationDetail.get_SchemaType()'.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.RefreshInstanceDetails(IOrganizationService crmService, Uri uriOfInstance)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DoDirectLogin(Boolean IsOnPrem)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2024-02-13 09:01:56  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2024-02-13 09:01:56  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 2024-02-13
Time	: 09:01:56
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================
```

Any tips on how to get back to the last official version?

**Comment by rappen** [comment]
I reverted to original version of `McTools.Xrm.Connection.dll` 1.2023.6.56 - and it still can't connect... 
Running from VS with one of my tools, using the same connection files, and it works fine.
Revert my whole XrmToolBox folder to one downloaded zip from your website - now everything works fine.

I'll just close this issue, even if I never found the actually reason.

**Comment by MscrmTools** [comment]
Reason is beta version comes with new SDK assemblies that seems to have some kind of breaking change... And reverting does not brings back older SDK assemblies. Something I need to work on when I find time
