### ISSUE TITLE
Issues Attempting to Connect to .crm11 Org

### ISSUE THREAD

**Issue by PeterUK** [MscrmTools/MscrmTools.Xrm.Connection#36]
Hi
I get connection errors when trying to connect to any of my UK data centre systems on the .crm11 domain,  I can conect fine to all my .crm4 orgs but the log produces the following after erroring out to a crm11 org (using version 1.2017.3.14)

I did manage to make a connection for a short time and it retrieved the entities but then timed out again.

Any help appreciated.

Peter

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/08/2017 09:00:06  ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/08/2017 09:00:06  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 23/08/2017
Time	: 09:00:06
Error	: Access is denied.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)

**Comment by MscrmTools** [comment]
Please update to latest version and you should be good

**Comment by PeterUK** [comment]
Thanks - all working now - Peter
