### ISSUE TITLE
Can't connect with user using alternate UPN Suffix

### ISSUE THREAD

**Issue by JDHannan** [MscrmTools/MscrmTools.Xrm.Connection#45]
We have a hosted environment with multiple clients running on it. The domain is "host"

However, there are multiple clients that have users with the same first and last name, so we can't set them all up in our AD as **host\firstname.lastname** and so we set up alternate UPN Suffixes for them so they can log into CRM as **firstname.lastname@companyname.com** (basically, their email address)

Such clients are not able to connect using the XRM Toolbox with error posted below but they can log into CRM just fine.

> Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2018-02-28 12:50:32 PM  Source	: System.ServiceModel
Method	: ReadResponse
Date	: 2018-02-28
Time	: 12:50:32 PM
Error	: ID3242: The security token could not be authenticated or authorized.
Stack Trace	: at System.ServiceModel.Security.WSTrustChannel.ReadResponse(Message response)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2018-02-28 12:50:32 PM  Unable to Login to Dynamics CRM

**Comment by MscrmTools** [comment]
The real comparison test is to use official Microsoft tools like Plugin Registration Tool to see if it can connect to CRM organisation.
If it can, then I guess I will have a new scenario to test and support.
If it can’t, then the problem is on Microsoft connection assemblies and I cannot do anything about it myself

Please test and report the result

**Comment by JDHannan** [comment]
Using the latest Plugin Registration Tool that I just downloaded, I was able to connect successfully as firstname.lastname@companyname.com
