### ISSUE TITLE
Unable to connect to crm 2011 on premise (v1.2018.4.22)

### ISSUE THREAD

**Issue by LuchoGa** [MscrmTools/MscrmTools.Xrm.Connection#52]
Hi all,

I am trying to connect to crm 2011 with this tool but it was not successful, hope you can help me, thanks in advance, here some input: 

1) Crm 2011 deployment working on https, and tls 1.2, active directory authentication
2) Installed framework4.6 on pc where tool (xrmtoolbox) is executed
3) This was found on the log:

![xrmtoolbox003](https://user-images.githubusercontent.com/40247839/41375949-3a31b95a-6f1d-11e8-94da-19632c05cf66.jpg)
![xrmtoolbox002](https://user-images.githubusercontent.com/40247839/41375950-3a55f5f4-6f1d-11e8-9f77-d1c88892f4e6.jpg)
![xrmtoolbox001](https://user-images.githubusercontent.com/40247839/41375951-3a74afbc-6f1d-11e8-988e-315269e42996.jpg)

==============================
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	6/13/2018 11:39:26 AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	6/13/2018 2:46:07 PM  Initialize CRM connection Started - AuthType: AD
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	6/13/2018 2:46:07 PM  Discovery URI is = https://<crmserver>:443/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	6/13/2018 2:46:07 PM  DiscoverOrganizations - Initializing Discovery Server Object with https://<crmserver>/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	6/13/2018 2:46:07 PM  DiscoverOrganizations - attempting to connect to CRM server @ https://<crmserver>/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	6/13/2018 2:46:08 PM  DiscoverOrganizations - created CRM server proxy configuration for https://<crmserver>/XRMServices/2011/Discovery.svc - duration: 00:00:00.7225457
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	6/13/2018 2:46:08 PM  DiscoverOrganizations - proxy requiring authentication type : ActiveDirectory 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	6/13/2018 2:46:08 PM  DiscoverOrganizations - service proxy created - total create duration: 00:00:00.7255561
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	6/13/2018 2:46:35 PM  ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	6/13/2018 2:46:35 PM  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 6/13/2018
Time	: 2:46:35 PM
Error	: The caller was not authenticated by the service.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.CommunicationObjectSecurityTokenProvider.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityProtocol.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.ClientSecurityChannel`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
======================================================================================================================
Inner Exception Level 1	: 
Source	: System.ServiceModel
Method	: ThrowIfNegotiationFault
Date	: 6/13/2018
Time	: 2:46:35 PM
Error	: The request for security token could not be satisfied because authentication failed.
Stack Trace	: at System.ServiceModel.Security.SecurityUtils.ThrowIfNegotiationFault(Message message, EndpointAddress target)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.GetNextOutgoingMessageBody(Message incomingMessage, SspiNegotiationTokenProviderState sspiState)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	6/13/2018 2:46:35 PM  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 6/13/2018
Time	: 2:46:35 PM
Error	: The caller was not authenticated by the service.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.CommunicationObjectSecurityTokenProvider.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityProtocol.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.ClientSecurityChannel`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System.ServiceModel
Method	: ThrowIfNegotiationFault
Date	: 6/13/2018
Time	: 2:46:35 PM
Error	: The request for security token could not be satisfied because authentication failed.
Stack Trace	: at System.ServiceModel.Security.SecurityUtils.ThrowIfNegotiationFault(Message message, EndpointAddress target)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.GetNextOutgoingMessageBody(Message incomingMessage, SspiNegotiationTokenProviderState sspiState)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	6/13/2018 2:46:35 PM  Unable to Login to Dynamics CRM

**Comment by MscrmTools** [comment]
First thing I would try is to not put domain name in username field
