### ISSUE TITLE
issue with connecting to C365 OnlineCRM 

### ISSUE THREAD

**Issue by tciesiolka** [MscrmTools/MscrmTools.Xrm.Connection#78]
Hello,
There seems to be an issue with connecting O365 CRM instance.
Version of CRM is :Version 1710 (9.1.0.35) online"
Version of XrmToolbox - latest.
My crm instace is configured for OnlineFederation. I`m connecting using username@company.com username.

Error is "Unable to Login to Dynamics CRM", details form log are below:

`Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	26.10.2018 10:07:22  Initialize CRM connection Started - AuthType: Office365
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	26.10.2018 10:07:22  Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	26.10.2018 10:07:22  DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	26.10.2018 10:07:22  DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	26.10.2018 10:07:23  DiscoverOrganizations - created CRM server proxy configuration for https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc - duration: 00:00:01.1320995
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	26.10.2018 10:07:23  DiscoverOrganizations - proxy requiring authentication type : OnlineFederation 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	26.10.2018 10:07:25  Source	: mscorlib
Method	: HandleReturnMessage
Date	: 26.10.2018
Time	: 10:07:25
Error	: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.Security.IWSTrustContract.Issue(Message message)
   at System.ServiceModel.Security.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederatedTokenWithOrgIdForCRM(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: Not Provided
Method	: Not Provided
Date	: 26.10.2018
Time	: 10:07:25
Error	: Authentication Failure
Stack Trace	: Not Provided
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	26.10.2018 10:07:25  Unable to Login to Dynamics CRM`

Do you possibly have any ideas on what i can try?
Moving back to older version does not help.

**Comment by SrinivasPodili** [comment]
Hi Team
I am also facing the same issue. attached full trace of error.
Error	: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.Se
[XrmToolBox_Connection-2019-11-05.log](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/files/3810136/XrmToolBox_Connection-2019-11-05.log)
rviceChannelProxy.Invoke(IMessage message)

**Comment by SrinivasPodili** [comment]
Can you please help with a workaround or a fix?

**Comment by SrinivasPodili** [comment]
@MscrmTools : Please have a look at this issue and let us know the next steps.

**Comment by MscrmTools** [comment]
I have no clue right now on what is happening. Can you try to login using the SDK control?

**Comment by SrinivasPodili** [comment]
I am getting this error only when connecting from Internet. Inside on premise/internal same tool is working without any issue.
attached the logs 
[XrmToolBox_Connection-2019-11-23.log](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/files/3882458/XrmToolBox_Connection-2019-11-23.log)

**Comment by SrinivasPodili** [comment]
@MscrmTools : I have uploaded the logs.

**Comment by MscrmTools** [comment]
Does it work with SDK Login control or not?
