### ISSUE TITLE
Unable to connect to D365 with MFA enabled

### ISSUE THREAD

**Issue by Markyb2018** [MscrmTools/MscrmTools.Xrm.Connection#81]
Hello,
I am having issues connecting to our D365 environment with MFA enabled. I have created the app registration as native in Azure and using the correct app ID. My connection string is 👍 

AuthType=OAuth;Username=Myusername;Password=Mypass;Url=https://ORG.api.crm4.dynamics.com;AppId=AppID;RedirectUri=https://login.microsoftonline.com/fb0392d0-5ebf-4ae9-9cc4-381316fe0dcb/oauth2/token;TokenCacheStorePath=c:\\Temp\\Oauth\\cache.txt;LoginPrompt=Always;RequireNewInstance=True;

Error log is

Date	: 14/11/2018
Time	: 11:42:01
Error	: Unauthorized Http Status Code (401) was expected in the response
Parameter name: response
Stack Trace	: at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.CreateFromUnauthorizedResponseCommon(IHttpWebResponse response)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverGlobalOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink, Boolean useGlobalDisco)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryOnlineServersList(ObservableCollection`1 svrs, OrganizationDetailCollection col, CrmOrgList orgsList, Uri trimToDiscoveryUri, Uri globalDiscoUriToUse)
======================================================================================================================
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	14/11/2018 11:42:01  No Organizations Found, Searched online. Region Setting = EMEA
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	14/11/2018 11:42:01  Unable to Login to Dynamics CRM

Any help would be appreciated as I am new to this.

Thanks

**Comment by rkelkar** [comment]
I am having the same issue. I get the prompt to login to my organization but it is not able to find my org.
The error is below:
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2/12/2019 3:02:13 PM  No Organizations Found, Searched online. Region Setting = NorthAmerica2
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	2/12/2019 3:02:13 PM  Unable to Login to Dynamics CRM

**Comment by zgrotov2** [comment]
I've had issues with this as well. I was able to use a client;s computer to login using the toolbox but could not use my own. Same credentials, same internet connection, etc. Are you able to login using the SDK tools?
