### ISSUE TITLE
ArgumentOutOfRangeException in loading About dialog

### ISSUE THREAD

**Issue by imranakram** [MscrmTools/MscrmTools.Xrm.Connection#83]
I’m adding an about dialog to the Plugin Registration Tool and this exception occurs randomly. Mostly it occurs when you go straight into opening the about dialog without clicking anywhere in the tree. And it just crashes the whole XTB. This is the stack trace:- 

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  Source=mscorlib
  StackTrace:
   at System.Collections.ArrayList.get_Item(Int32 index) in f:\dd\ndp\clr\src\BCL\system\collections\arraylist.cs:line 173
   at System.Windows.Forms.ToolStripItemCollection.get_Item(Int32 index)
   at McTools.Xrm.Connection.WinForms.CrmConnectionStatusBar.SetMessage(String message)
   at XrmToolBox.New.NewForm.<>c__DisplayClass64_0.<StatusBarMessenger_SendMessageToStatusBar>g__Mi|1()
   at XrmToolBox.New.PluginForm.<>c__DisplayClass28_0.<StatusBarMessager_SendMessageToStatusBar>g__Mi|0()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.SafeNativeMethods.MessageBox(HandleRef hWnd, String text, String caption, Int32 type)
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   at System.Windows.Forms.MessageBox.Show(String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon)
   at XrmToolBox.Program.Main(String[] args)
```

I can see that it must be coming from this method in the `CrmConnectionStatusBar` here

```
public void SetMessage(string message)
{
     ToolStripStatusLabel label = (ToolStripStatusLabel)Items[1];
```

Now trouble is I’ve never worked with the Xrm.Connections project and have no idea what this `Items[]` collection is representing. The assembly is also signed, when I tried to replace it in my local debug folder, it fails saying that the assembly should be signed and so on.  Please let me know how to proceed

**Comment by imranakram** [comment]
ping @shytikov

**Comment by MscrmTools** [comment]
@imranakram is it still happening? 

I’m reviewing all remaining issues... sorry it took so long to answer you
