### ISSUE TITLE
Unable to connect to the remote server using XRMToolbox version v1.2018.10.29

### ISSUE THREAD

**Issue by jorgeabiad** [MscrmTools/MscrmTools.Xrm.Connection#84]
Hello,
This is the trace log for the error I am getting. We are using D365 version 9.1.0.2001

************************************************************************************************************
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/01/2019 12:56:30 PM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/01/2019 1:18:42 PM  Source	: System.ServiceModel
Method	: Retrieve
Date	: 23/01/2019
Time	: 1:18:42 PM
Error	: Metadata contains a reference that cannot be resolved: 'https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: GetResponse
Date	: 23/01/2019
Time	: 1:18:42 PM
Error	: Unable to connect to the remote server
Stack Trace	: at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================
Inner Exception Level 2	: 
Source	: System
Method	: DoConnect
Date	: 23/01/2019
Time	: 1:18:42 PM
Error	: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.112.68.136:443
Stack Trace	: at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/01/2019 1:18:42 PM  Unable to Login to Dynamics CRM

**************************************************************************************************************
Our Quality instance is : https://orgname.crm4.dynamics.com

**Comment by umerjaved** [comment]
Hi,

I wonder if there was any resolution to the issue since we are facing the same error when connecting to Dynamics 365 online.

Thanks
