### ISSUE TITLE
Windows Server - Data Transporter Unable to Login

### ISSUE THREAD

**Issue by oliverfrodrigues** [MscrmTools/MscrmTools.Xrm.Connection#90]
I am using Data Transporter tool from XrmToolbox to transfer data between environments
I am using the latest version (1.2019.2.32) and when I am using on my local machine everything is fine.. but I actually need to perform this task directly from the server where CRM is installed (D365 On-Premise  8.2.5.4).. the server has access to the internet
the tool itself is working fine for pretty much all plugins, but when I use the Data Transporter I can't connect to two environments, it throws an unusual exception (below)
I also tested the "A sample tool with multiple connections" from the prerelease version, and it works fine 

![image](https://user-images.githubusercontent.com/29526513/58101817-2d058680-7bd8-11e9-8b6e-acc92618f6f4.png)

************** Exception Text **************
System.Exception: Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XrmToolBox.New.NewForm.<ManageConnectionControl>b__58_2(Object sender, ConnectionSucceedEventArgs e)
   at McTools.Xrm.Connection.ConnectionManager.SendSuccessMessage(IOrganizationService service, List`1 parameters)
   at McTools.Xrm.Connection.WinForms.FormHelper.AskForConnection(Object connectionParameter, Action preConnectionRequestAction)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MscrmTools** [comment]
Please see with the author of the tool that must not use connection result properly.
The repo is [here](https://github.com/bcolpaert/Colso.Xrm.DataTransporter/issues)
