### ISSUE TITLE
Unable to install plugins unhandled exception error

### ISSUE THREAD

**Issue by eddie-haynes** [MscrmTools/MscrmTools.Xrm.Connection#95]
Hi all,

I am fairly new to XRMToolbox and Dynamics in general and would appreciate some help as I've delved into the depths of the internet for hours and still unable to resolve.

I am sat behind a company VPN however am still able to connect XRMToolbox to my Dynamics instances via the SDK login control and my Office 365 credentials, so no issues there. The problem is that when I try to install any plugin from the store I get an unhandled exception error with _The remote name could not be resolved: 'packages.nuget.org'._

![image](https://user-images.githubusercontent.com/31478767/62308660-b3163700-b47d-11e9-9402-8c8d0cc3d020.png)

With the details showing:
************** Exception Text **************
System.Net.WebException: The remote name could not be resolved: 'packages.nuget.org'
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
   at NuGet.RedirectedHttpClient.EnsureClient()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
   at NuGet.RedirectedHttpClient.get_CachedClient()
   at NuGet.RedirectedHttpClient.get_Uri()
   at NuGet.DataServicePackageRepository.get_Context()
   at NuGet.DataServicePackageRepository.FindPackage(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
   at XrmToolBox.PluginsStore.StoreFromPortal.PrepareInstallationPackages(List`1 pluginsToInstall, BackgroundWorker worker)
   at XrmToolBox.PluginsStore.StoreFormFromPortal.<tsbInstall_Click>b__35_5(Object sbw, DoWorkEventArgs evt)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument).

As I am not very experienced with this any help would be very much appreciated, although I have a hunch it may be something to do with the connection/company firewall etc?

Thanks!

**Comment by MscrmTools** [comment]
It seems you are not able to reach Nuget servers.
If you are using a proxy, then there is a gear icon to define the proxy to use in the Plugins Store.
If the proxy is not enough, then it’s more complicated to explain from my phone but there is ways to download plugins directly

**Comment by eddie-haynes** [comment]
Thanks! I'm not using a proxy. Strange as it was working for a while then one day just decided not to. Any information on how to directly install the plugins would be great!
